// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCategoryBudget = `-- name: CountCategoryBudget :one
SELECT COUNT(*) AS cnt
FROM budgets
WHERE ` + "`" + `year_month` + "`" + ` = ? AND category_id = ?
`

type CountCategoryBudgetParams struct {
	YearMonth  string        `json:"year_month"`
	CategoryID sql.NullInt64 `json:"category_id"`
}

// カテゴリ別予算の重複チェック。
func (q *Queries) CountCategoryBudget(ctx context.Context, arg CountCategoryBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryBudget, arg.YearMonth, arg.CategoryID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countMonthWideBudget = `-- name: CountMonthWideBudget :one
SELECT COUNT(*) AS cnt
FROM budgets
WHERE ` + "`" + `year_month` + "`" + ` = ? AND category_id IS NULL
`

// 月全体予算（category_id IS NULL）の重複チェック。
// MySQL の UNIQUE 制約は NULL の重複を許すため、アプリ側でも検査する。
func (q *Queries) CountMonthWideBudget(ctx context.Context, yearMonth string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonthWideBudget, yearMonth)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createBudget = `-- name: CreateBudget :execlastid
INSERT INTO budgets (category_id, ` + "`" + `year_month` + "`" + `, amount)
VALUES (?, ?, ?)
`

type CreateBudgetParams struct {
	CategoryID sql.NullInt64 `json:"category_id"`
	YearMonth  string        `json:"year_month"`
	Amount     int32         `json:"amount"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createBudget, arg.CategoryID, arg.YearMonth, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets
WHERE id = ?
`

func (q *Queries) DeleteBudget(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBudget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBudget = `-- name: GetBudget :one
SELECT
  b.id, b.category_id, b.` + "`" + `year_month` + "`" + `, b.amount, b.created_at, b.updated_at,
  c.name AS category_name
FROM budgets b
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.id = ?
`

type GetBudgetRow struct {
	ID           int64          `json:"id"`
	CategoryID   sql.NullInt64  `json:"category_id"`
	YearMonth    string         `json:"year_month"`
	Amount       int32          `json:"amount"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CategoryName sql.NullString `json:"category_name"`
}

func (q *Queries) GetBudget(ctx context.Context, id int64) (GetBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, getBudget, id)
	var i GetBudgetRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.YearMonth,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT
  b.id, b.category_id, b.` + "`" + `year_month` + "`" + `, b.amount, b.created_at, b.updated_at,
  c.name AS category_name
FROM budgets b
LEFT JOIN categories c ON c.id = b.category_id
WHERE b.` + "`" + `year_month` + "`" + ` = ?
ORDER BY (b.category_id IS NOT NULL), c.name
`

type ListBudgetsRow struct {
	ID           int64          `json:"id"`
	CategoryID   sql.NullInt64  `json:"category_id"`
	YearMonth    string         `json:"year_month"`
	Amount       int32          `json:"amount"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	CategoryName sql.NullString `json:"category_name"`
}

func (q *Queries) ListBudgets(ctx context.Context, yearMonth string) ([]ListBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets, yearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.YearMonth,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :execrows
UPDATE budgets
SET amount = ?
WHERE id = ?
`

type UpdateBudgetParams struct {
	Amount int32 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBudget, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
