// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
	"database/sql"
)

const countCategoryByNameType = `-- name: CountCategoryByNameType :one
SELECT COUNT(*) AS cnt
FROM categories
WHERE name = ? AND type = ?
`

type CountCategoryByNameTypeParams struct {
	Name string         `json:"name"`
	Type CategoriesType `json:"type"`
}

func (q *Queries) CountCategoryByNameType(ctx context.Context, arg CountCategoryByNameTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryByNameType, arg.Name, arg.Type)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countCategoryByNameTypeExcludingID = `-- name: CountCategoryByNameTypeExcludingID :one
SELECT COUNT(*) AS cnt
FROM categories
WHERE name = ? AND type = ? AND id <> ?
`

type CountCategoryByNameTypeExcludingIDParams struct {
	Name string         `json:"name"`
	Type CategoriesType `json:"type"`
	ID   int64          `json:"id"`
}

func (q *Queries) CountCategoryByNameTypeExcludingID(ctx context.Context, arg CountCategoryByNameTypeExcludingIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryByNameTypeExcludingID, arg.Name, arg.Type, arg.ID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countCategoryUsage = `-- name: CountCategoryUsage :one
SELECT
  (SELECT COUNT(*) FROM transactions t WHERE t.category_id = ?) +
  (SELECT COUNT(*) FROM budgets b WHERE b.category_id = ?) AS usage_count
`

type CountCategoryUsageParams struct {
	CategoryID   int64         `json:"category_id"`
	CategoryID_2 sql.NullInt64 `json:"category_id_2"`
}

func (q *Queries) CountCategoryUsage(ctx context.Context, arg CountCategoryUsageParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCategoryUsage, arg.CategoryID, arg.CategoryID_2)
	var usage_count int32
	err := row.Scan(&usage_count)
	return usage_count, err
}

const createCategory = `-- name: CreateCategory :execlastid
INSERT INTO categories (name, type)
VALUES (?, ?)
`

type CreateCategoryParams struct {
	Name string         `json:"name"`
	Type CategoriesType `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory, arg.Name, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, type, created_at, updated_at
FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, created_at, updated_at
FROM categories
ORDER BY type, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByType = `-- name: ListCategoriesByType :many
SELECT id, name, type, created_at, updated_at
FROM categories
WHERE (? IS NULL OR type = ?)
ORDER BY type, name
`

type ListCategoriesByTypeParams struct {
	Type NullCategoriesType `json:"type"`
}

func (q *Queries) ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByType, arg.Type, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET name = ?, type = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name string         `json:"name"`
	Type CategoriesType `json:"type"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.Type, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
