// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CategoriesType string

const (
	CategoriesTypeIncome  CategoriesType = "income"
	CategoriesTypeExpense CategoriesType = "expense"
)

func (e *CategoriesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoriesType(s)
	case string:
		*e = CategoriesType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoriesType: %T", src)
	}
	return nil
}

type NullCategoriesType struct {
	CategoriesType CategoriesType `json:"categories_type"`
	Valid          bool           `json:"valid"` // Valid is true if CategoriesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoriesType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoriesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoriesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoriesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoriesType), nil
}

type TransactionsType string

const (
	TransactionsTypeIncome  TransactionsType = "income"
	TransactionsTypeExpense TransactionsType = "expense"
)

func (e *TransactionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsType(s)
	case string:
		*e = TransactionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsType: %T", src)
	}
	return nil
}

type NullTransactionsType struct {
	TransactionsType TransactionsType `json:"transactions_type"`
	Valid            bool             `json:"valid"` // Valid is true if TransactionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsType), nil
}

type Budget struct {
	ID         int64         `json:"id"`
	CategoryID sql.NullInt64 `json:"category_id"`
	YearMonth  string        `json:"year_month"`
	Amount     int32         `json:"amount"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type Category struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      CategoriesType `json:"type"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID         int64            `json:"id"`
	OccurredOn time.Time        `json:"occurred_on"`
	Amount     int32            `json:"amount"`
	Type       TransactionsType `json:"type"`
	CategoryID int64            `json:"category_id"`
	Memo       sql.NullString   `json:"memo"`
	CreatedAt  time.Time        `json:"created_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}
