// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error)
	DeleteTransaction(ctx context.Context, id int64) (int64, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetTransaction(ctx context.Context, id int64) (GetTransactionRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
