// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package db

import (
	"context"
	"time"
)

const getMonthlyTotals = `-- name: GetMonthlyTotals :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN type = 'income'  THEN amount ELSE 0 END), 0) AS SIGNED) AS income,
  CAST(COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0) AS SIGNED) AS expense
FROM transactions
WHERE occurred_on BETWEEN ? AND ?
`

type GetMonthlyTotalsParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetMonthlyTotalsRow struct {
	Income  int64 `json:"income"`
	Expense int64 `json:"expense"`
}

func (q *Queries) GetMonthlyTotals(ctx context.Context, arg GetMonthlyTotalsParams) (GetMonthlyTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyTotals, arg.StartDate, arg.EndDate)
	var i GetMonthlyTotalsRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}

const listExpenseByCategory = `-- name: ListExpenseByCategory :many
SELECT
  t.category_id,
  c.name AS category_name,
  CAST(SUM(t.amount) AS SIGNED) AS total
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.type = 'expense'
  AND t.occurred_on BETWEEN ? AND ?
GROUP BY t.category_id, c.name
ORDER BY total DESC
`

type ListExpenseByCategoryParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type ListExpenseByCategoryRow struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	Total        int64  `json:"total"`
}

func (q *Queries) ListExpenseByCategory(ctx context.Context, arg ListExpenseByCategoryParams) ([]ListExpenseByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpenseByCategory, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpenseByCategoryRow{}
	for rows.Next() {
		var i ListExpenseByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyTrend = `-- name: ListMonthlyTrend :many
SELECT
  DATE_FORMAT(occurred_on, '%Y-%m') AS ym,
  CAST(COALESCE(SUM(CASE WHEN type = 'income'  THEN amount ELSE 0 END), 0) AS SIGNED) AS income,
  CAST(COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0) AS SIGNED) AS expense
FROM transactions
WHERE occurred_on BETWEEN ? AND ?
GROUP BY DATE_FORMAT(occurred_on, '%Y-%m')
ORDER BY ym
`

type ListMonthlyTrendParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type ListMonthlyTrendRow struct {
	Ym      string `json:"ym"`
	Income  int64  `json:"income"`
	Expense int64  `json:"expense"`
}

func (q *Queries) ListMonthlyTrend(ctx context.Context, arg ListMonthlyTrendParams) ([]ListMonthlyTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonthlyTrend, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyTrendRow{}
	for rows.Next() {
		var i ListMonthlyTrendRow
		if err := rows.Scan(&i.Ym, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
