// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :execlastid
INSERT INTO transactions (occurred_on, amount, type, category_id, memo)
VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	OccurredOn time.Time        `json:"occurred_on"`
	Amount     int32            `json:"amount"`
	Type       TransactionsType `json:"type"`
	CategoryID int64            `json:"category_id"`
	Memo       sql.NullString   `json:"memo"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTransaction,
		arg.OccurredOn,
		arg.Amount,
		arg.Type,
		arg.CategoryID,
		arg.Memo,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTransaction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTransaction = `-- name: GetTransaction :one
SELECT
  t.id, t.occurred_on, t.amount, t.type, t.category_id,
  c.name AS category_name,
  t.memo, t.created_at, t.updated_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.id = ?
`

type GetTransactionRow struct {
	ID           int64            `json:"id"`
	OccurredOn   time.Time        `json:"occurred_on"`
	Amount       int32            `json:"amount"`
	Type         TransactionsType `json:"type"`
	CategoryID   int64            `json:"category_id"`
	CategoryName string           `json:"category_name"`
	Memo         sql.NullString   `json:"memo"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

func (q *Queries) GetTransaction(ctx context.Context, id int64) (GetTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.OccurredOn,
		&i.Amount,
		&i.Type,
		&i.CategoryID,
		&i.CategoryName,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id, t.occurred_on, t.amount, t.type, t.category_id,
  c.name AS category_name,
  t.memo, t.created_at, t.updated_at
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.occurred_on BETWEEN ? AND ?
  AND (? IS NULL OR t.type = ?)
  AND (? IS NULL OR t.category_id = ?)
ORDER BY t.occurred_on DESC, t.id DESC
`

type ListTransactionsParams struct {
	StartDate  time.Time            `json:"start_date"`
	EndDate    time.Time            `json:"end_date"`
	Type       NullTransactionsType `json:"type"`
	CategoryID sql.NullInt64        `json:"category_id"`
}

type ListTransactionsRow struct {
	ID           int64            `json:"id"`
	OccurredOn   time.Time        `json:"occurred_on"`
	Amount       int32            `json:"amount"`
	Type         TransactionsType `json:"type"`
	CategoryID   int64            `json:"category_id"`
	CategoryName string           `json:"category_name"`
	Memo         sql.NullString   `json:"memo"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Type,
		arg.CategoryID,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredOn,
			&i.Amount,
			&i.Type,
			&i.CategoryID,
			&i.CategoryName,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :execrows
UPDATE transactions
SET occurred_on = ?, amount = ?, type = ?, category_id = ?, memo = ?
WHERE id = ?
`

type UpdateTransactionParams struct {
	OccurredOn time.Time        `json:"occurred_on"`
	Amount     int32            `json:"amount"`
	Type       TransactionsType `json:"type"`
	CategoryID int64            `json:"category_id"`
	Memo       sql.NullString   `json:"memo"`
	ID         int64            `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTransaction,
		arg.OccurredOn,
		arg.Amount,
		arg.Type,
		arg.CategoryID,
		arg.Memo,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
